/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Camilo
 */
public class JIempleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIempleados
     */
    public JIempleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JLabel();
        txtCodempleados = new javax.swing.JLabel();
        txtcedulaemple = new javax.swing.JLabel();
        txtNombrepersonaemple = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txttelemple = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDirecemple = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtSalario1 = new javax.swing.JLabel();
        btnGuardarEmpleado1 = new javax.swing.JButton();
        btnactualizarem = new javax.swing.JButton();
        btndespedido = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaEmplados = new javax.swing.JTable();

        setClosable(true);

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel26.setText("Horas Trabajadas ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setText("Codigo");

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel30.setText("Nombre");

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel31.setText("Cedula");

        txtHoras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCodempleados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtcedulaemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNombrepersonaemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel28.setText("Telefono");

        txttelemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel29.setText("Direccion");

        txtDirecemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel33.setText("Salario");

        txtSalario1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardarEmpleado1.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/GuardarTodo.png"))); // NOI18N
        btnGuardarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleado1ActionPerformed(evt);
            }
        });

        btnactualizarem.setBackground(new java.awt.Color(204, 204, 204));
        btnactualizarem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Actualizar (2).png"))); // NOI18N
        btnactualizarem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaremActionPerformed(evt);
            }
        });

        btndespedido.setBackground(new java.awt.Color(204, 204, 204));
        btndespedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btndespedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndespedidoActionPerformed(evt);
            }
        });

        TablaEmplados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRE", "CODIGO", "TELEFONO", "DIRECCION", "SALARIO", "HORAS TRABAJADAS", "SUELDO"
            }
        ));
        TablaEmplados.setRowHeight(23);
        TablaEmplados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpladosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaEmplados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(11, 11, 11)
                                .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtCodempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtNombrepersonaemple, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(19, 19, 19)
                                        .addComponent(txtcedulaemple, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(7, 7, 7)
                                        .addComponent(txttelemple, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtDirecemple, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnactualizarem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btndespedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(544, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtCodempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(txtNombrepersonaemple, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(txtcedulaemple, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txttelemple, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txtDirecemple, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(txtSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizarem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btndespedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEmpleado1ActionPerformed

    private void btnactualizaremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaremActionPerformed

    }//GEN-LAST:event_btnactualizaremActionPerformed

    private void btndespedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndespedidoActionPerformed

    }//GEN-LAST:event_btndespedidoActionPerformed

    private void TablaEmpladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpladosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TablaEmpladosMouseClicked

    public JTable getTablaEmplados() {
        return TablaEmplados;
    }

    public void setTablaEmplados(JTable TablaEmplados) {
        this.TablaEmplados = TablaEmplados;
    }

    public JButton getBtnGuardarEmpleado1() {
        return btnGuardarEmpleado1;
    }

    public void setBtnGuardarEmpleado1(JButton btnGuardarEmpleado1) {
        this.btnGuardarEmpleado1 = btnGuardarEmpleado1;
    }

    public JButton getBtnactualizarem() {
        return btnactualizarem;
    }

    public void setBtnactualizarem(JButton btnactualizarem) {
        this.btnactualizarem = btnactualizarem;
    }

    public JButton getBtndespedido() {
        return btndespedido;
    }

    public void setBtndespedido(JButton btndespedido) {
        this.btndespedido = btndespedido;
    }

    public JLabel getTxtCodempleados() {
        return txtCodempleados;
    }

    public void setTxtCodempleados(JLabel txtCodempleados) {
        this.txtCodempleados = txtCodempleados;
    }

    public JLabel getTxtDirecemple() {
        return txtDirecemple;
    }

    public void setTxtDirecemple(JLabel txtDirecemple) {
        this.txtDirecemple = txtDirecemple;
    }

    public JLabel getTxtHoras() {
        return txtHoras;
    }

    public void setTxtHoras(JLabel txtHoras) {
        this.txtHoras = txtHoras;
    }



    public JLabel getTxtNombrepersonaemple() {
        return txtNombrepersonaemple;
    }

    public void setTxtNombrepersonaemple(JLabel txtNombrepersonaemple) {
        this.txtNombrepersonaemple = txtNombrepersonaemple;
    }

    public JLabel getTxtSalario1() {
        return txtSalario1;
    }

    public void setTxtSalario1(JLabel txtSalario1) {
        this.txtSalario1 = txtSalario1;
    }

    public JLabel getTxtcedulaemple() {
        return txtcedulaemple;
    }

    public void setTxtcedulaemple(JLabel txtcedulaemple) {
        this.txtcedulaemple = txtcedulaemple;
    }

    public JLabel getTxttelemple() {
        return txttelemple;
    }

    public void setTxttelemple(JLabel txttelemple) {
        this.txttelemple = txttelemple;
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmplados;
    private javax.swing.JButton btnGuardarEmpleado1;
    private javax.swing.JButton btnactualizarem;
    private javax.swing.JButton btndespedido;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel txtCodempleados;
    private javax.swing.JLabel txtDirecemple;
    private javax.swing.JLabel txtHoras;
    private javax.swing.JLabel txtNombrepersonaemple;
    private javax.swing.JLabel txtSalario1;
    private javax.swing.JLabel txtcedulaemple;
    private javax.swing.JLabel txttelemple;
    // End of variables declaration//GEN-END:variables
}
