/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Estudiante
 */
public class JIMeseros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIRegisplato
     */
     public JIMeseros() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnGuardarpedido = new javax.swing.JButton();
        btnEliminarpedido = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSplatos = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txttel = new javax.swing.JLabel();
        txtNombrepersona = new javax.swing.JLabel();
        txtcedula = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablePedido = new javax.swing.JTable();

        setClosable(true);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarpedido.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/GuardarTodo.png"))); // NOI18N
        btnGuardarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarpedidoActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardarpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 50));

        btnEliminarpedido.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btnEliminarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarpedidoActionPerformed(evt);
            }
        });
        jPanel11.add(btnEliminarpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 50));

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 0));

        jPanel39.setBackground(new java.awt.Color(0, 0, 0));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Platos del Día");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel26.setText("Telefono");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jSplatos.setModel(new javax.swing.SpinnerListModel(new String[] {""}));
        jPanel11.add(jSplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setText("Platos");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel30.setText("Nombre");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel31.setText("Cedula");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel32.setText("Email");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txttel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, 20));

        txtNombrepersona.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtNombrepersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, 20));

        txtcedula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 20));

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, 20));

        TablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO"
            }
        ));
        TablePedido.setRowHeight(23);
        TablePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePedidoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablePedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 507, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarpedidoActionPerformed
       
    }//GEN-LAST:event_btnGuardarpedidoActionPerformed

    private void btnEliminarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarpedidoActionPerformed
      
    }//GEN-LAST:event_btnEliminarpedidoActionPerformed

    private void TablePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePedidoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TablePedidoMouseClicked

    public JTable getTablePedido() {
        return TablePedido;
    }

    public void setTablePedido(JTable TablePedido) {
        this.TablePedido = TablePedido;
    }

    public JButton getBtnEliminarpedido() {
        return btnEliminarpedido;
    }

    public void setBtnEliminarpedido(JButton btnEliminarpedido) {
        this.btnEliminarpedido = btnEliminarpedido;
    }

    public JButton getBtnGuardarpedido() {
        return btnGuardarpedido;
    }

    public void setBtnGuardarpedido(JButton btnGuardarpedido) {
        this.btnGuardarpedido = btnGuardarpedido;
    }

    public JLabel getTxtNombrepersona() {
        return txtNombrepersona;
    }

    public void setTxtNombrepersona(JLabel txtNombrepersona) {
        this.txtNombrepersona = txtNombrepersona;
    }

    public JLabel getTxtcedula() {
        return txtcedula;
    }

    public void setTxtcedula(JLabel txtcedula) {
        this.txtcedula = txtcedula;
    }

    public JLabel getTxttel() {
        return txttel;
    }

    public void setTxttel(JLabel txttel) {
        this.txttel = txttel;
    }

    public JSpinner getjSplatos() {
        return jSplatos;
    }

    public void setjSplatos(JSpinner jSplatos) {
        this.jSplatos = jSplatos;
    }

    public JLabel getTxtID() {
        return txtID;
    }

    public void setTxtID(JLabel txtID) {
        this.txtID = txtID;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePedido;
    private javax.swing.JButton btnEliminarpedido;
    private javax.swing.JButton btnGuardarpedido;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSplatos;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtNombrepersona;
    private javax.swing.JLabel txtcedula;
    private javax.swing.JLabel txttel;
    // End of variables declaration//GEN-END:variables
}
