/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Estudiante
 */
public class JIMempleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIRegisplato
     */
     public JIMempleados() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnactualizarem = new javax.swing.JButton();
        btndespedido = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnGuardarEmpleado1 = new javax.swing.JButton();
        txtNombrepersonaemple = new javax.swing.JTextField();
        txtIDemple = new javax.swing.JTextField();
        txtCodempleados2 = new javax.swing.JTextField();
        txtcedulaemple1 = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txttelemple1 = new javax.swing.JTextField();
        txtDirecemple1 = new javax.swing.JTextField();
        txtSalario2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaEmplados = new javax.swing.JTable();

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnactualizarem.setBackground(new java.awt.Color(204, 204, 204));
        btnactualizarem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Actualizar (2).png"))); // NOI18N
        btnactualizarem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaremActionPerformed(evt);
            }
        });
        jPanel11.add(btnactualizarem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 50));

        btndespedido.setBackground(new java.awt.Color(204, 204, 204));
        btndespedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btndespedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndespedidoActionPerformed(evt);
            }
        });
        jPanel11.add(btndespedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 50));

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 0));

        jPanel39.setBackground(new java.awt.Color(0, 0, 0));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Empleados");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel26.setText("Horas Trabajadas ");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setText("Codigo");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel30.setText("Nombre");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel31.setText("Cedula");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel32.setText("Email");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel28.setText("Telefono");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel29.setText("Direccion");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel33.setText("Salario");
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnGuardarEmpleado1.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/GuardarTodo.png"))); // NOI18N
        btnGuardarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleado1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardarEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 50));

        txtNombrepersonaemple.setBackground(new java.awt.Color(153, 153, 153));
        txtNombrepersonaemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtNombrepersonaemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        txtIDemple.setBackground(new java.awt.Color(153, 153, 153));
        txtIDemple.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtIDemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, -1));

        txtCodempleados2.setBackground(new java.awt.Color(153, 153, 153));
        txtCodempleados2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtCodempleados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, -1));

        txtcedulaemple1.setBackground(new java.awt.Color(153, 153, 153));
        txtcedulaemple1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(txtcedulaemple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        txtHoras.setBackground(new java.awt.Color(204, 204, 204));
        txtHoras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasActionPerformed(evt);
            }
        });
        jPanel11.add(txtHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, -1));

        txttelemple1.setBackground(new java.awt.Color(204, 204, 204));
        txttelemple1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelemple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelemple1ActionPerformed(evt);
            }
        });
        jPanel11.add(txttelemple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        txtDirecemple1.setBackground(new java.awt.Color(204, 204, 204));
        txtDirecemple1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDirecemple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecemple1ActionPerformed(evt);
            }
        });
        jPanel11.add(txtDirecemple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 110, -1));

        txtSalario2.setBackground(new java.awt.Color(204, 204, 204));
        txtSalario2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSalario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalario2ActionPerformed(evt);
            }
        });
        jPanel11.add(txtSalario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, -1));

        TablaEmplados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRE", "CODIGO", "TELEFONO", "DIRECCION", "SALARIO", "HORAS TRABAJADAS", "SUELDO"
            }
        ));
        TablaEmplados.setRowHeight(23);
        TablaEmplados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpladosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaEmplados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(743, 743, 743))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizaremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaremActionPerformed
       
    }//GEN-LAST:event_btnactualizaremActionPerformed

    private void btndespedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndespedidoActionPerformed
      
    }//GEN-LAST:event_btndespedidoActionPerformed

    private void TablaEmpladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpladosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TablaEmpladosMouseClicked

    private void btnGuardarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEmpleado1ActionPerformed

    private void txtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasActionPerformed

    private void txttelemple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelemple1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelemple1ActionPerformed

    private void txtDirecemple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecemple1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecemple1ActionPerformed

    private void txtSalario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalario2ActionPerformed

    public JTable getTablaEmplados() {
        return TablaEmplados;
    }

    public void setTablaEmplados(JTable TablaEmplados) {
        this.TablaEmplados = TablaEmplados;
    }

    public JButton getBtnactualizarem() {
        return btnactualizarem;
    }

    public void setBtnactualizarem(JButton btnactualizarem) {
        this.btnactualizarem = btnactualizarem;
    }




    public JButton getBtnGuardarEmpleado() {
        return btnactualizarem;
    }

    public void setBtnGuardarEmpleado(JButton btnGuardarEmpleado) {
        this.btnactualizarem = btnGuardarEmpleado;
    }

    public JButton getBtndespedido() {
        return btndespedido;
    }

    public void setBtndespedido(JButton btndespedido) {
        this.btndespedido = btndespedido;
    }

    public JButton getBtnGuardarEmpleado1() {
        return btnGuardarEmpleado1;
    }

    public void setBtnGuardarEmpleado1(JButton btnGuardarEmpleado1) {
        this.btnGuardarEmpleado1 = btnGuardarEmpleado1;
    }

    public JTextField getTxtCodempleados2() {
        return txtCodempleados2;
    }

    public void setTxtCodempleados2(JTextField txtCodempleados2) {
        this.txtCodempleados2 = txtCodempleados2;
    }

    public JTextField getTxtDirecemple1() {
        return txtDirecemple1;
    }

    public void setTxtDirecemple1(JTextField txtDirecemple1) {
        this.txtDirecemple1 = txtDirecemple1;
    }

    public JTextField getTxtHoras() {
        return txtHoras;
    }

    public void setTxtHoras(JTextField txtHoras) {
        this.txtHoras = txtHoras;
    }

    public JTextField getTxtIDemple() {
        return txtIDemple;
    }

    public void setTxtIDemple(JTextField txtIDemple) {
        this.txtIDemple = txtIDemple;
    }

    public JTextField getTxtNombrepersonaemple() {
        return txtNombrepersonaemple;
    }

    public void setTxtNombrepersonaemple(JTextField txtNombrepersonaemple) {
        this.txtNombrepersonaemple = txtNombrepersonaemple;
    }

    public JTextField getTxtSalario2() {
        return txtSalario2;
    }

    public void setTxtSalario2(JTextField txtSalario2) {
        this.txtSalario2 = txtSalario2;
    }

    public JTextField getTxtcedulaemple1() {
        return txtcedulaemple1;
    }

    public void setTxtcedulaemple1(JTextField txtcedulaemple1) {
        this.txtcedulaemple1 = txtcedulaemple1;
    }

    public JTextField getTxttelemple1() {
        return txttelemple1;
    }

    public void setTxttelemple1(JTextField txttelemple1) {
        this.txttelemple1 = txttelemple1;
    }



    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmplados;
    private javax.swing.JButton btnGuardarEmpleado1;
    private javax.swing.JButton btnactualizarem;
    private javax.swing.JButton btndespedido;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCodempleados2;
    private javax.swing.JTextField txtDirecemple1;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtIDemple;
    private javax.swing.JTextField txtNombrepersonaemple;
    private javax.swing.JTextField txtSalario2;
    private javax.swing.JTextField txtcedulaemple1;
    private javax.swing.JTextField txttelemple1;
    // End of variables declaration//GEN-END:variables
}
