/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Estudiante
 */
public class JIRegisplato extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIRegisplato
     */
     public JIRegisplato() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtProteina = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btnGuardarPlato = new javax.swing.JButton();
        btnEditarPlato = new javax.swing.JButton();
        btnEliminarPlato = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCantidaddepersonas = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtAcompañamiento1 = new javax.swing.JTextField();
        jSbebida = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPRECIO = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablePlatos = new javax.swing.JTable();

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel23.setText("Cantidad de Persona:");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        txtProteina.setBackground(new java.awt.Color(204, 204, 204));
        txtProteina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtProteina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProteinaActionPerformed(evt);
            }
        });
        jPanel11.add(txtProteina, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel25.setText("Proteina:");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnGuardarPlato.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/GuardarTodo.png"))); // NOI18N
        btnGuardarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPlatoActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 50));

        btnEditarPlato.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Actualizar (2).png"))); // NOI18N
        btnEditarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlatoActionPerformed(evt);
            }
        });
        jPanel11.add(btnEditarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 100, 50));

        btnEliminarPlato.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btnEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatoActionPerformed(evt);
            }
        });
        jPanel11.add(btnEliminarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 50));

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 0));

        jPanel39.setBackground(new java.awt.Color(0, 0, 0));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Platos del Día");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel26.setText("tiene bebida?");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        txtCantidaddepersonas.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidaddepersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCantidaddepersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidaddepersonasActionPerformed(evt);
            }
        });
        jPanel11.add(txtCantidaddepersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel27.setText("Acompañamiento:");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        txtAcompañamiento1.setBackground(new java.awt.Color(204, 204, 204));
        txtAcompañamiento1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAcompañamiento1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcompañamiento1KeyTyped(evt);
            }
        });
        jPanel11.add(txtAcompañamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 30));

        jSbebida.setModel(new javax.swing.SpinnerListModel(new String[] {"si ", "no"}));
        jPanel11.add(jSbebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel24.setText("Nombre:");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));

        txtID.setBackground(new java.awt.Color(204, 204, 204));
        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel11.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel28.setText("ID:");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtNOMBRE.setBackground(new java.awt.Color(204, 204, 204));
        txtNOMBRE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMBREActionPerformed(evt);
            }
        });
        jPanel11.add(txtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel29.setText("Precio:");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtPRECIO.setBackground(new java.awt.Color(204, 204, 204));
        txtPRECIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPRECIO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPRECIOKeyTyped(evt);
            }
        });
        jPanel11.add(txtPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 150, 30));

        TablePlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO"
            }
        ));
        TablePlatos.setRowHeight(23);
        TablePlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePlatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablePlatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPlatoActionPerformed
       
    }//GEN-LAST:event_btnGuardarPlatoActionPerformed

    private void btnEditarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlatoActionPerformed
        
    }//GEN-LAST:event_btnEditarPlatoActionPerformed

    private void btnEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoActionPerformed
      
    }//GEN-LAST:event_btnEliminarPlatoActionPerformed

    private void txtProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinaActionPerformed

    private void txtCantidaddepersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidaddepersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidaddepersonasActionPerformed

    private void txtAcompañamiento1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcompañamiento1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcompañamiento1KeyTyped

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMBREActionPerformed

    private void txtPRECIOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPRECIOKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRECIOKeyTyped

    private void TablePlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePlatosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TablePlatosMouseClicked

    public JTable getTablePlatos() {
        return TablePlatos;
    }

    public void setTablePlatos(JTable TablePlatos) {
        this.TablePlatos = TablePlatos;
    }

    public JButton getBtnEditarPlato() {
        return btnEditarPlato;
    }

    public void setBtnEditarPlato(JButton btnEditarPlato) {
        this.btnEditarPlato = btnEditarPlato;
    }

    public JButton getBtnEliminarPlato() {
        return btnEliminarPlato;
    }

    public void setBtnEliminarPlato(JButton btnEliminarPlato) {
        this.btnEliminarPlato = btnEliminarPlato;
    }

    public JButton getBtnGuardarPlato() {
        return btnGuardarPlato;
    }

    public void setBtnGuardarPlato(JButton btnGuardarPlato) {
        this.btnGuardarPlato = btnGuardarPlato;
    }

    public JSpinner getjSbebida() {
        return jSbebida;
    }

    public void setjSbebida(JSpinner jSbebida) {
        this.jSbebida = jSbebida;
    }

    public JTextField getTxtAcompañamiento2() {
        return txtPRECIO;
    }

    public void setTxtAcompañamiento2(JTextField txtAcompañamiento2) {
        this.txtPRECIO = txtAcompañamiento2;
    }

    public JTextField getTxtCantidaddepersonas() {
        return txtCantidaddepersonas;
    }

    public void setTxtCantidaddepersonas(JTextField txtCantidaddepersonas) {
        this.txtCantidaddepersonas = txtCantidaddepersonas;
    }

    public JTextField getTxtProteina() {
        return txtProteina;
    }

    public void setTxtProteina(JTextField txtProteina) {
        this.txtProteina = txtProteina;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public void setTxtID(JTextField txtID) {
        this.txtID = txtID;
    }

    public JTextField getTxtNOMBRE() {
        return txtNOMBRE;
    }

    public void setTxtNOMBRE(JTextField txtNOMBRE) {
        this.txtNOMBRE = txtNOMBRE;
    }

    public JTextField getTxtPRECIO() {
        return txtPRECIO;
    }

    public void setTxtPRECIO(JTextField txtPRECIO) {
        this.txtPRECIO = txtPRECIO;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePlatos;
    private javax.swing.JButton btnEditarPlato;
    private javax.swing.JButton btnEliminarPlato;
    private javax.swing.JButton btnGuardarPlato;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JSpinner jSbebida;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtAcompañamiento1;
    private javax.swing.JTextField txtCantidaddepersonas;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtPRECIO;
    private javax.swing.JTextField txtProteina;
    // End of variables declaration//GEN-END:variables
}
