/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

import javax.swing.JToolBar;


/**
 *
 * @author Camilo
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
     public MDIPrincipal() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnventas = new javax.swing.JButton();
        Panelventanas = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnmitemesero = new javax.swing.JMenu();
        mnmhacerpedido = new javax.swing.JMenuItem();
        mnmmostrarfactura = new javax.swing.JMenuItem();
        mnmitecajero = new javax.swing.JMenu();
        cobrar = new javax.swing.JMenuItem();
        mnmiteadministrador = new javax.swing.JMenu();
        mnmRegistrarplato = new javax.swing.JMenuItem();
        mnmRepoteempleados = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        btnventas.setText("PedidoRapido");
        btnventas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnventas.setFocusable(false);
        btnventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnventas);

        Panelventanas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelventanasLayout = new javax.swing.GroupLayout(Panelventanas);
        Panelventanas.setLayout(PanelventanasLayout);
        PanelventanasLayout.setHorizontalGroup(
            PanelventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelventanasLayout.setVerticalGroup(
            PanelventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(Panelventanas)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelventanas))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Adobe Express - file (1).jpg"))); // NOI18N

        mnmitemesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/003-camarero.png"))); // NOI18N
        mnmitemesero.setText("Mesero");

        mnmhacerpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/002-men.png"))); // NOI18N
        mnmhacerpedido.setText("Hacer pedido");
        mnmhacerpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmhacerpedidoActionPerformed(evt);
            }
        });
        mnmitemesero.add(mnmhacerpedido);

        mnmmostrarfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-cuenta-bancaria.png"))); // NOI18N
        mnmmostrarfactura.setText("Mostrar Factura");
        mnmmostrarfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmmostrarfacturaActionPerformed(evt);
            }
        });
        mnmitemesero.add(mnmmostrarfactura);

        jMenuBar1.add(mnmitemesero);

        mnmitecajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-cajero.png"))); // NOI18N
        mnmitecajero.setText("Cajero");

        cobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/004-dinero.png"))); // NOI18N
        cobrar.setText("Cobrar");
        mnmitecajero.add(cobrar);

        jMenuBar1.add(mnmitecajero);

        mnmiteadministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-blogger.png"))); // NOI18N
        mnmiteadministrador.setText("Administardor");

        mnmRegistrarplato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-registro.png"))); // NOI18N
        mnmRegistrarplato.setText("Registrar plato");
        mnmiteadministrador.add(mnmRegistrarplato);

        mnmRepoteempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/005-informe-de-analisis.png"))); // NOI18N
        mnmRepoteempleados.setText("Reporte empleados");
        mnmRepoteempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmRepoteempleadosActionPerformed(evt);
            }
        });
        mnmiteadministrador.add(mnmRepoteempleados);

        jMenuBar1.add(mnmiteadministrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnmhacerpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmhacerpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmhacerpedidoActionPerformed

    private void mnmmostrarfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmmostrarfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmmostrarfacturaActionPerformed

    private void mnmRepoteempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmRepoteempleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmRepoteempleadosActionPerformed

    public JButton getBtnventas() {
        return btnventas;
    }

    public void setBtnventas(JButton btnventas) {
        this.btnventas = btnventas;
    }

    public JMenuItem getCobrar() {
        return cobrar;
    }

    public void setCobrar(JMenuItem cobrar) {
        this.cobrar = cobrar;
    }

  

    public JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    public void setjCheckBoxMenuItem1(JCheckBoxMenuItem jCheckBoxMenuItem1) {
        this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
    }


    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

  
    public JToolBar getjToolBar2() {
        return jToolBar2;
    }

    public void setjToolBar2(JToolBar jToolBar2) {
        this.jToolBar2 = jToolBar2;
    }

    public JMenuItem getMnmRegistrarplato() {
        return mnmRegistrarplato;
    }

    public void setMnmRegistrarplato(JMenuItem mnmRegistrarplato) {
        this.mnmRegistrarplato = mnmRegistrarplato;
    }

    public JMenuItem getMnmRepoteempleados() {
        return mnmRepoteempleados;
    }

    public void setMnmRepoteempleados(JMenuItem mnmRepoteempleados) {
        this.mnmRepoteempleados = mnmRepoteempleados;
    }

    public JMenuItem getMnmhacerpedido() {
        return mnmhacerpedido;
    }

    public void setMnmhacerpedido(JMenuItem mnmhacerpedido) {
        this.mnmhacerpedido = mnmhacerpedido;
    }

    public JMenu getMnmiteadministrador() {
        return mnmiteadministrador;
    }

    public void setMnmiteadministrador(JMenu mnmiteadministrador) {
        this.mnmiteadministrador = mnmiteadministrador;
    }

    public JMenu getMnmitecajero() {
        return mnmitecajero;
    }

    public void setMnmitecajero(JMenu mnmitecajero) {
        this.mnmitecajero = mnmitecajero;
    }

    public JMenu getMnmitemesero() {
        return mnmitemesero;
    }

    public void setMnmitemesero(JMenu mnmitemesero) {
        this.mnmitemesero = mnmitemesero;
    }

    public JMenuItem getMnmmostrarfactura() {
        return mnmmostrarfactura;
    }

    public void setMnmmostrarfactura(JMenuItem mnmmostrarfactura) {
        this.mnmmostrarfactura = mnmmostrarfactura;
    }

    public JDesktopPane getPanelventanas() {
        return Panelventanas;
    }

    public void setPanelventanas(JDesktopPane Panelventanas) {
        this.Panelventanas = Panelventanas;
    }

    




    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Panelventanas;
    private javax.swing.JButton btnventas;
    private javax.swing.JMenuItem cobrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnmRegistrarplato;
    private javax.swing.JMenuItem mnmRepoteempleados;
    private javax.swing.JMenuItem mnmhacerpedido;
    private javax.swing.JMenu mnmiteadministrador;
    private javax.swing.JMenu mnmitecajero;
    private javax.swing.JMenu mnmitemesero;
    private javax.swing.JMenuItem mnmmostrarfactura;
    // End of variables declaration//GEN-END:variables



}
