/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Camilo
 */
public class MDIprueba extends javax.swing.JFrame {

    /**
     * Creates new form MDIprueba
     */
    public MDIprueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        btnventas = new javax.swing.JButton();
        panelventanas = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnmitemesero = new javax.swing.JMenu();
        mnmhacerpedido = new javax.swing.JMenuItem();
        mnmmostrarfactura = new javax.swing.JMenuItem();
        mnmitecajero = new javax.swing.JMenu();
        cobrar = new javax.swing.JMenuItem();
        mnmiteadministrador = new javax.swing.JMenu();
        mnmRegistrarplato = new javax.swing.JMenuItem();
        mnmRepoteempleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        btnventas.setText("PedidoRapido");
        btnventas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnventas.setFocusable(false);
        btnventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnventas);

        desktopPane.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 400, 40);

        panelventanas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelventanasLayout = new javax.swing.GroupLayout(panelventanas);
        panelventanas.setLayout(panelventanasLayout);
        panelventanasLayout.setHorizontalGroup(
            panelventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        panelventanasLayout.setVerticalGroup(
            panelventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        desktopPane.add(panelventanas);
        panelventanas.setBounds(0, 50, 340, 210);

        mnmitemesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/003-camarero.png"))); // NOI18N
        mnmitemesero.setText("Mesero");

        mnmhacerpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/002-men.png"))); // NOI18N
        mnmhacerpedido.setText("Hacer pedido");
        mnmhacerpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmhacerpedidoActionPerformed(evt);
            }
        });
        mnmitemesero.add(mnmhacerpedido);

        mnmmostrarfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-cuenta-bancaria.png"))); // NOI18N
        mnmmostrarfactura.setText("Mostrar Factura");
        mnmmostrarfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmmostrarfacturaActionPerformed(evt);
            }
        });
        mnmitemesero.add(mnmmostrarfactura);

        jMenuBar1.add(mnmitemesero);

        mnmitecajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-cajero.png"))); // NOI18N
        mnmitecajero.setText("Cajero");

        cobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/004-dinero.png"))); // NOI18N
        cobrar.setText("Cobrar");
        mnmitecajero.add(cobrar);

        jMenuBar1.add(mnmitecajero);

        mnmiteadministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-blogger.png"))); // NOI18N
        mnmiteadministrador.setText("Administardor");

        mnmRegistrarplato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/001-registro.png"))); // NOI18N
        mnmRegistrarplato.setText("Registrar plato");
        mnmiteadministrador.add(mnmRegistrarplato);

        mnmRepoteempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/005-informe-de-analisis.png"))); // NOI18N
        mnmRepoteempleados.setText("Reporte empleados");
        mnmRepoteempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmRepoteempleadosActionPerformed(evt);
            }
        });
        mnmiteadministrador.add(mnmRepoteempleados);

        jMenuBar1.add(mnmiteadministrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnmhacerpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmhacerpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmhacerpedidoActionPerformed

    private void mnmmostrarfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmmostrarfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmmostrarfacturaActionPerformed

    private void mnmRepoteempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmRepoteempleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmRepoteempleadosActionPerformed

    public JButton getBtnventas() {
        return btnventas;
    }

    public void setBtnventas(JButton btnventas) {
        this.btnventas = btnventas;
    }

    public JMenuItem getCobrar() {
        return cobrar;
    }

    public void setCobrar(JMenuItem cobrar) {
        this.cobrar = cobrar;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenuItem getMnmRegistrarplato() {
        return mnmRegistrarplato;
    }

    public void setMnmRegistrarplato(JMenuItem mnmRegistrarplato) {
        this.mnmRegistrarplato = mnmRegistrarplato;
    }

    public JMenuItem getMnmRepoteempleados() {
        return mnmRepoteempleados;
    }

    public void setMnmRepoteempleados(JMenuItem mnmRepoteempleados) {
        this.mnmRepoteempleados = mnmRepoteempleados;
    }

    public JMenuItem getMnmhacerpedido() {
        return mnmhacerpedido;
    }

    public void setMnmhacerpedido(JMenuItem mnmhacerpedido) {
        this.mnmhacerpedido = mnmhacerpedido;
    }

    public JMenu getMnmiteadministrador() {
        return mnmiteadministrador;
    }

    public void setMnmiteadministrador(JMenu mnmiteadministrador) {
        this.mnmiteadministrador = mnmiteadministrador;
    }

    public JMenu getMnmitecajero() {
        return mnmitecajero;
    }

    public void setMnmitecajero(JMenu mnmitecajero) {
        this.mnmitecajero = mnmitecajero;
    }

    public JMenu getMnmitemesero() {
        return mnmitemesero;
    }

    public void setMnmitemesero(JMenu mnmitemesero) {
        this.mnmitemesero = mnmitemesero;
    }

    public JMenuItem getMnmmostrarfactura() {
        return mnmmostrarfactura;
    }

    public void setMnmmostrarfactura(JMenuItem mnmmostrarfactura) {
        this.mnmmostrarfactura = mnmmostrarfactura;
    }

    public JDesktopPane getPanelventanas() {
        return panelventanas;
    }

    public void setPanelventanas(JDesktopPane panelventanas) {
        this.panelventanas = panelventanas;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnventas;
    private javax.swing.JMenuItem cobrar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnmRegistrarplato;
    private javax.swing.JMenuItem mnmRepoteempleados;
    private javax.swing.JMenuItem mnmhacerpedido;
    private javax.swing.JMenu mnmiteadministrador;
    private javax.swing.JMenu mnmitecajero;
    private javax.swing.JMenu mnmitemesero;
    private javax.swing.JMenuItem mnmmostrarfactura;
    private javax.swing.JDesktopPane panelventanas;
    // End of variables declaration//GEN-END:variables

}
